[project]
name = "tinymesh"
version = "0.1.0"
description = "Tinygrad-native learning over sparse structures through space and time"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.11"
dependencies = [
    "tinygrad @ git+https://github.com/tinygrad/tinygrad.git@6ea7d366fa92842c0bc8b7b080e26e83a7406252",
]

[build-system]
requires = ["uv_build>=0.11.29,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
docs = [
    "zensical==0.0.51",
]
lint = [
    "mypy==1.19.1",
    "ruff==0.14.10",
]

[tool.mypy]
files = ["src/tinymesh"]
check_untyped_defs = true
strict_equality = true
warn_redundant_casts = true
warn_unreachable = true
warn_unused_configs = true

[tool.ruff]
exclude = ["submodules"]
indent-width = 2
line-length = 150
preview = true
target-version = "py311"

[tool.ruff.lint]
select = [
    "A",
    "C416",
    "E112",
    "E113",
    "E203",
    "E272",
    "E275",
    "E303",
    "E304",
    "E501",
    "E702",
    "E703",
    "E71",
    "E72",
    "E731",
    "F",
    "FURB110",
    "RET506",
    "RET507",
    "RUF018",
    "UP039",
    "W191",
    "W291",
    "W293",
    "W6",
]
