[paper."i-jepa"]
arxiv = "2301.08243v3"
license = "https://arxiv.org/licenses/nonexclusive-distrib/1.0/"

[paper."i-jepa".citation]
type = "inproceedings"
key = "Assran_2023_CVPR"
title = "Self-Supervised Learning From Images With a Joint-Embedding Predictive Architecture"
author = "Assran, Mahmoud and Duval, Quentin and Misra, Ishan and Bojanowski, Piotr and Vincent, Pascal and Rabbat, Michael and LeCun, Yann and Ballas, Nicolas"
booktitle = "Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR)"
month = "June"
year = "2023"
pages = "15619--15629"
url = "https://openaccess.thecvf.com/content/CVPR2023/html/Assran_Self-Supervised_Learning_From_Images_With_a_Joint-Embedding_Predictive_Architecture_CVPR_2023_paper.html"

[paper."graph-jepa"]
arxiv = "2309.16014v3"
license = "https://creativecommons.org/licenses/by/4.0/"

[paper."graph-jepa".citation]
type = "article"
key = "skenderi2025graph"
title = "Graph-level Representation Learning with Joint-Embedding Predictive Architectures"
author = "Skenderi, Geri and Li, Hang and Tang, Jiliang and Cristani, Marco"
journal = "Transactions on Machine Learning Research"
year = "2025"
url = "https://openreview.net/forum?id=v47f4DwYZb"

[paper."gine"]
arxiv = "1905.12265v3"
license = "https://arxiv.org/licenses/nonexclusive-distrib/1.0/"

[paper."gine".citation]
type = "inproceedings"
key = "Hu_2020_ICLR"
title = "Strategies for Pre-training Graph Neural Networks"
author = "Hu, Weihua and Liu, Bowen and Gomes, Joseph and Zitnik, Marinka and Liang, Percy and Pande, Vijay and Leskovec, Jure"
booktitle = "International Conference on Learning Representations"
year = "2020"
url = "https://openreview.net/forum?id=HJlWWJSFDH"

[paper."v-jepa"]
arxiv = "2404.08471v1"
license = "https://creativecommons.org/licenses/by/4.0/"

[paper."v-jepa".citation]
type = "article"
key = "Bardes_2024_VJEPA"
title = "Revisiting Feature Prediction for Learning Visual Representations from Video"
author = "Bardes, Adrien and Garrido, Quentin and Ponce, Jean and Chen, Xinlei and Rabbat, Michael and LeCun, Yann and Assran, Mahmoud and Ballas, Nicolas"
journal = "arXiv preprint arXiv:2404.08471"
year = "2024"
url = "https://arxiv.org/abs/2404.08471v1"
