name: Documentation

on:
  pull_request:
    paths:
      - ".github/workflows/docs.yml"
      - "docs/**"
      - "pyproject.toml"
      - "src/tinymesh/**"
      - "uv.lock"
      - "zensical.toml"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/docs.yml"
      - "docs/**"
      - "pyproject.toml"
      - "src/tinymesh/**"
      - "uv.lock"
      - "zensical.toml"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "0.11.32"
      - run: uv run --locked --only-group docs zensical build --clean --strict
      - if: github.event_name == 'push'
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with:
          path: site

  deploy:
    if: github.event_name == 'push'
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6
      - id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5
